# powerlevel10k
source ~/powerlevel10k/powerlevel10k.zsh-theme
[ -f ~/.p10k.zsh ] && source ~/.p10k.zsh

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# kubectl
alias k=kubectl
alias kgp='k get pods'
alias kgpn='kgp -n'
alias kgs='k get services'
alias kgsn='kgs -n'

source <(kubectl completion zsh)
