# powerlevel10k
source ~/powerlevel10k/powerlevel10k.zsh-theme
[ -f ~/.p10k.zsh ] && source ~/.p10k.zsh

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# kubectl
alias k=kubectl
alias kgp='k get pods'
alias kgpn='kgp -n'
alias kgs='k get services'
alias kgsn='kgs -n'

source <(kubectl completion zsh)

# fix permissions on /run/host-services/ssh-auth.sock when running on Mac
# based on: https://github.com/docker/for-mac/issues/410
[ $SSH_AUTH_SOCK = /run/host-services/ssh-auth.sock ] && sudo chmod 666 $SSH_AUTH_SOCK
